/**
 * Robot Catalogue Seed
 * 36 robots × 6 elements (VOLT, PYRO, CRYO, NANO, VOID, IRON)
 * 3 tiers per element (T1, T2, T3) × 2 variants = 6 per element
 */

export const ROBOT_SEEDS = [
  // ─── VOLT (6) ─────────────────────────────────────────────────────────────
  { slug: "volt-striker-mk1",    element: "VOLT", tier: "T1", display_name: "Volt Striker Mk.I",    base_hp: 80, base_attack: 65, base_defense: 40, base_speed: 75, base_energy: 10, energy_regen: 3, strong_vs: ["CRYO","IRON"], weak_vs: ["NANO"], biome_bonus: { CITY: 15, GRASSLAND: 5 }, gmo_cost: 0, is_starter: true },
  { slug: "volt-sentinel-mk1",   element: "VOLT", tier: "T1", display_name: "Volt Sentinel Mk.I",   base_hp: 95, base_attack: 50, base_defense: 60, base_speed: 55, base_energy: 10, energy_regen: 2, strong_vs: ["CRYO","IRON"], weak_vs: ["NANO"], biome_bonus: { CITY: 10 }, gmo_cost: 300, is_starter: false },
  { slug: "volt-blitz-mk2",      element: "VOLT", tier: "T2", display_name: "Volt Blitz Mk.II",     base_hp: 90, base_attack: 80, base_defense: 45, base_speed: 95, base_energy: 12, energy_regen: 3, strong_vs: ["CRYO","IRON"], weak_vs: ["NANO"], biome_bonus: { CITY: 20 }, gmo_cost: 1200, is_starter: false },
  { slug: "volt-aegis-mk2",      element: "VOLT", tier: "T2", display_name: "Volt Aegis Mk.II",     base_hp: 110, base_attack: 60, base_defense: 80, base_speed: 60, base_energy: 12, energy_regen: 2, strong_vs: ["CRYO","IRON"], weak_vs: ["NANO"], biome_bonus: { CITY: 15 }, gmo_cost: 1500, is_starter: false },
  { slug: "volt-apex-mk3",       element: "VOLT", tier: "T3", display_name: "Volt Apex Mk.III",     base_hp: 110, base_attack: 100, base_defense: 60, base_speed: 110, base_energy: 15, energy_regen: 4, strong_vs: ["CRYO","IRON"], weak_vs: ["NANO"], biome_bonus: { CITY: 25 }, gmo_cost: 5000, is_starter: false },
  { slug: "volt-throne-mk3",     element: "VOLT", tier: "T3", display_name: "Volt Throne Mk.III",   base_hp: 130, base_attack: 80, base_defense: 100, base_speed: 75, base_energy: 15, energy_regen: 3, strong_vs: ["CRYO","IRON"], weak_vs: ["NANO"], biome_bonus: { CITY: 20 }, gmo_cost: 6000, is_starter: false },

  // ─── PYRO (6) ─────────────────────────────────────────────────────────────
  { slug: "pyro-torch-mk1",      element: "PYRO", tier: "T1", display_name: "Pyro Torch Mk.I",      base_hp: 75, base_attack: 70, base_defense: 35, base_speed: 70, base_energy: 10, energy_regen: 3, strong_vs: ["CRYO","NANO"], weak_vs: ["VOID","IRON"], biome_bonus: { DESERT: 20 }, gmo_cost: 0, is_starter: true },
  { slug: "pyro-guardian-mk1",   element: "PYRO", tier: "T1", display_name: "Pyro Guardian Mk.I",   base_hp: 90, base_attack: 55, base_defense: 55, base_speed: 50, base_energy: 10, energy_regen: 2, strong_vs: ["CRYO","NANO"], weak_vs: ["VOID","IRON"], biome_bonus: { DESERT: 15 }, gmo_cost: 350, is_starter: false },
  { slug: "pyro-inferno-mk2",    element: "PYRO", tier: "T2", display_name: "Pyro Inferno Mk.II",   base_hp: 85, base_attack: 90, base_defense: 40, base_speed: 80, base_energy: 12, energy_regen: 3, strong_vs: ["CRYO","NANO"], weak_vs: ["VOID","IRON"], biome_bonus: { DESERT: 25 }, gmo_cost: 1300, is_starter: false },
  { slug: "pyro-bulwark-mk2",    element: "PYRO", tier: "T2", display_name: "Pyro Bulwark Mk.II",   base_hp: 105, base_attack: 65, base_defense: 75, base_speed: 55, base_energy: 12, energy_regen: 2, strong_vs: ["CRYO","NANO"], weak_vs: ["VOID","IRON"], biome_bonus: { DESERT: 20 }, gmo_cost: 1600, is_starter: false },
  { slug: "pyro-dragon-mk3",     element: "PYRO", tier: "T3", display_name: "Pyro Dragon Mk.III",   base_hp: 105, base_attack: 110, base_defense: 55, base_speed: 95, base_energy: 15, energy_regen: 4, strong_vs: ["CRYO","NANO"], weak_vs: ["VOID","IRON"], biome_bonus: { DESERT: 30 }, gmo_cost: 5500, is_starter: false },
  { slug: "pyro-citadel-mk3",    element: "PYRO", tier: "T3", display_name: "Pyro Citadel Mk.III",  base_hp: 125, base_attack: 85, base_defense: 95, base_speed: 65, base_energy: 15, energy_regen: 3, strong_vs: ["CRYO","NANO"], weak_vs: ["VOID","IRON"], biome_bonus: { DESERT: 25 }, gmo_cost: 6500, is_starter: false },

  // ─── CRYO (6) ─────────────────────────────────────────────────────────────
  { slug: "cryo-frost-mk1",      element: "CRYO", tier: "T1", display_name: "Cryo Frost Mk.I",      base_hp: 85, base_attack: 60, base_defense: 50, base_speed: 65, base_energy: 10, energy_regen: 2, strong_vs: ["VOLT","PYRO"], weak_vs: ["VOID","IRON"], biome_bonus: { SNOWFIELD: 25 }, gmo_cost: 0, is_starter: true },
  { slug: "cryo-shield-mk1",     element: "CRYO", tier: "T1", display_name: "Cryo Shield Mk.I",     base_hp: 100, base_attack: 45, base_defense: 70, base_speed: 45, base_energy: 10, energy_regen: 2, strong_vs: ["VOLT","PYRO"], weak_vs: ["VOID","IRON"], biome_bonus: { SNOWFIELD: 20 }, gmo_cost: 300, is_starter: false },
  { slug: "cryo-blizzard-mk2",   element: "CRYO", tier: "T2", display_name: "Cryo Blizzard Mk.II",  base_hp: 95, base_attack: 80, base_defense: 55, base_speed: 75, base_energy: 12, energy_regen: 3, strong_vs: ["VOLT","PYRO"], weak_vs: ["VOID","IRON"], biome_bonus: { SNOWFIELD: 30 }, gmo_cost: 1400, is_starter: false },
  { slug: "cryo-fortress-mk2",   element: "CRYO", tier: "T2", display_name: "Cryo Fortress Mk.II",  base_hp: 120, base_attack: 55, base_defense: 90, base_speed: 50, base_energy: 12, energy_regen: 2, strong_vs: ["VOLT","PYRO"], weak_vs: ["VOID","IRON"], biome_bonus: { SNOWFIELD: 25 }, gmo_cost: 1700, is_starter: false },
  { slug: "cryo-avalanche-mk3",  element: "CRYO", tier: "T3", display_name: "Cryo Avalanche Mk.III",base_hp: 115, base_attack: 105, base_defense: 65, base_speed: 90, base_energy: 15, energy_regen: 4, strong_vs: ["VOLT","PYRO"], weak_vs: ["VOID","IRON"], biome_bonus: { SNOWFIELD: 35 }, gmo_cost: 6000, is_starter: false },
  { slug: "cryo-glacier-mk3",    element: "CRYO", tier: "T3", display_name: "Cryo Glacier Mk.III",  base_hp: 140, base_attack: 70, base_defense: 110, base_speed: 55, base_energy: 15, energy_regen: 3, strong_vs: ["VOLT","PYRO"], weak_vs: ["VOID","IRON"], biome_bonus: { SNOWFIELD: 30 }, gmo_cost: 7000, is_starter: false },

  // ─── NANO (6) ─────────────────────────────────────────────────────────────
  { slug: "nano-drone-mk1",      element: "NANO", tier: "T1", display_name: "Nano Drone Mk.I",      base_hp: 70, base_attack: 55, base_defense: 45, base_speed: 85, base_energy: 12, energy_regen: 4, strong_vs: ["IRON","VOID"], weak_vs: ["VOLT","PYRO"], biome_bonus: { CITY: 10, GRASSLAND: 10 }, gmo_cost: 0, is_starter: true },
  { slug: "nano-medic-mk1",      element: "NANO", tier: "T1", display_name: "Nano Medic Mk.I",      base_hp: 85, base_attack: 40, base_defense: 55, base_speed: 65, base_energy: 14, energy_regen: 4, strong_vs: ["IRON","VOID"], weak_vs: ["VOLT","PYRO"], biome_bonus: { CITY: 15 }, gmo_cost: 400, is_starter: false },
  { slug: "nano-swarm-mk2",      element: "NANO", tier: "T2", display_name: "Nano Swarm Mk.II",     base_hp: 80, base_attack: 75, base_defense: 50, base_speed: 100, base_energy: 14, energy_regen: 4, strong_vs: ["IRON","VOID"], weak_vs: ["VOLT","PYRO"], biome_bonus: { CITY: 20 }, gmo_cost: 1500, is_starter: false },
  { slug: "nano-fortress-mk2",   element: "NANO", tier: "T2", display_name: "Nano Fortress Mk.II",  base_hp: 100, base_attack: 55, base_defense: 75, base_speed: 70, base_energy: 14, energy_regen: 3, strong_vs: ["IRON","VOID"], weak_vs: ["VOLT","PYRO"], biome_bonus: { CITY: 15 }, gmo_cost: 1800, is_starter: false },
  { slug: "nano-singularity-mk3",element: "NANO", tier: "T3", display_name: "Nano Singularity Mk.III", base_hp: 100, base_attack: 95, base_defense: 65, base_speed: 115, base_energy: 18, energy_regen: 5, strong_vs: ["IRON","VOID"], weak_vs: ["VOLT","PYRO"], biome_bonus: { CITY: 30 }, gmo_cost: 7000, is_starter: false },
  { slug: "nano-colossus-mk3",   element: "NANO", tier: "T3", display_name: "Nano Colossus Mk.III", base_hp: 120, base_attack: 75, base_defense: 100, base_speed: 80, base_energy: 18, energy_regen: 4, strong_vs: ["IRON","VOID"], weak_vs: ["VOLT","PYRO"], biome_bonus: { CITY: 25 }, gmo_cost: 8000, is_starter: false },

  // ─── VOID (6) ─────────────────────────────────────────────────────────────
  { slug: "void-shade-mk1",      element: "VOID", tier: "T1", display_name: "Void Shade Mk.I",      base_hp: 72, base_attack: 68, base_defense: 38, base_speed: 80, base_energy: 10, energy_regen: 3, strong_vs: ["NANO","PYRO"], weak_vs: ["IRON"], biome_bonus: { CITY: 5, SNOWFIELD: 5 }, gmo_cost: 0, is_starter: true },
  { slug: "void-warden-mk1",     element: "VOID", tier: "T1", display_name: "Void Warden Mk.I",     base_hp: 88, base_attack: 52, base_defense: 58, base_speed: 60, base_energy: 10, energy_regen: 2, strong_vs: ["NANO","PYRO"], weak_vs: ["IRON"], biome_bonus: { CITY: 10 }, gmo_cost: 450, is_starter: false },
  { slug: "void-phantom-mk2",    element: "VOID", tier: "T2", display_name: "Void Phantom Mk.II",   base_hp: 88, base_attack: 88, base_defense: 45, base_speed: 95, base_energy: 12, energy_regen: 3, strong_vs: ["NANO","PYRO"], weak_vs: ["IRON"], biome_bonus: { CITY: 15, SNOWFIELD: 10 }, gmo_cost: 1600, is_starter: false },
  { slug: "void-bastion-mk2",    element: "VOID", tier: "T2", display_name: "Void Bastion Mk.II",   base_hp: 108, base_attack: 62, base_defense: 78, base_speed: 62, base_energy: 12, energy_regen: 2, strong_vs: ["NANO","PYRO"], weak_vs: ["IRON"], biome_bonus: { CITY: 10 }, gmo_cost: 1900, is_starter: false },
  { slug: "void-annihilator-mk3",element: "VOID", tier: "T3", display_name: "Void Annihilator Mk.III",base_hp: 108, base_attack: 115, base_defense: 60, base_speed: 108, base_energy: 15, energy_regen: 4, strong_vs: ["NANO","PYRO"], weak_vs: ["IRON"], biome_bonus: { CITY: 25 }, gmo_cost: 8000, is_starter: false },
  { slug: "void-sovereign-mk3",  element: "VOID", tier: "T3", display_name: "Void Sovereign Mk.III",base_hp: 128, base_attack: 88, base_defense: 105, base_speed: 78, base_energy: 15, energy_regen: 3, strong_vs: ["NANO","PYRO"], weak_vs: ["IRON"], biome_bonus: { CITY: 20 }, gmo_cost: 9000, is_starter: false },

  // ─── IRON (6) ─────────────────────────────────────────────────────────────
  { slug: "iron-brawler-mk1",    element: "IRON", tier: "T1", display_name: "Iron Brawler Mk.I",    base_hp: 100, base_attack: 60, base_defense: 60, base_speed: 50, base_energy: 8, energy_regen: 2, strong_vs: ["VOLT","VOID"], weak_vs: ["NANO"], biome_bonus: { GRASSLAND: 10, DESERT: 5 }, gmo_cost: 0, is_starter: true },
  { slug: "iron-sentinel-mk1",   element: "IRON", tier: "T1", display_name: "Iron Sentinel Mk.I",   base_hp: 115, base_attack: 45, base_defense: 80, base_speed: 40, base_energy: 8, energy_regen: 2, strong_vs: ["VOLT","VOID"], weak_vs: ["NANO"], biome_bonus: { GRASSLAND: 5 }, gmo_cost: 400, is_starter: false },
  { slug: "iron-crusher-mk2",    element: "IRON", tier: "T2", display_name: "Iron Crusher Mk.II",   base_hp: 110, base_attack: 85, base_defense: 65, base_speed: 60, base_energy: 10, energy_regen: 2, strong_vs: ["VOLT","VOID"], weak_vs: ["NANO"], biome_bonus: { GRASSLAND: 15 }, gmo_cost: 1700, is_starter: false },
  { slug: "iron-titan-mk2",      element: "IRON", tier: "T2", display_name: "Iron Titan Mk.II",     base_hp: 130, base_attack: 65, base_defense: 95, base_speed: 45, base_energy: 10, energy_regen: 2, strong_vs: ["VOLT","VOID"], weak_vs: ["NANO"], biome_bonus: { GRASSLAND: 10 }, gmo_cost: 2000, is_starter: false },
  { slug: "iron-juggernaut-mk3", element: "IRON", tier: "T3", display_name: "Iron Juggernaut Mk.III",base_hp: 135, base_attack: 110, base_defense: 80, base_speed: 70, base_energy: 12, energy_regen: 3, strong_vs: ["VOLT","VOID"], weak_vs: ["NANO"], biome_bonus: { GRASSLAND: 20 }, gmo_cost: 9000, is_starter: false },
  { slug: "iron-colossus-mk3",   element: "IRON", tier: "T3", display_name: "Iron Colossus Mk.III", base_hp: 160, base_attack: 80, base_defense: 120, base_speed: 50, base_energy: 12, energy_regen: 2, strong_vs: ["VOLT","VOID"], weak_vs: ["NANO"], biome_bonus: { GRASSLAND: 15 }, gmo_cost: 10000, is_starter: false },
];
